version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - C:\Users\DELL\Documents\docker\frontend

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - C:\Users\DELL\Documents\docker\frontend

    command: ["npm", "run", "test"]